import "./globals.css";

export const metadata = {
  title: {
    absolute: "",
    default: " E-commerce",
    template: "%s | E-commerce",
  },
  description: "Generated by Next.js",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
